### ISSUE TITLE
module 'whisper' has no attribute 'load_model'

### ISSUE THREAD

**Issue by guilh98** [TirrouOussama/speach_to_text#2]
Seeing your code has been very helpful to me, and thank you very much for contributing the code.
I encountered some errors while running your code. Could you please help me clarify my confusion.

module 'whisper' has no attribute 'load_model'

model = whisper.load_model("small")
result = model.transcribe('output.wav')
print(result['text'])

pip install whisper

whisper version 1.1.10

**Comment by TirrouOussama** [comment]
pip install -U openai-whisper  and re-download the small model its outdated

**Comment by TirrouOussama** [comment]
pip install -U openai-whisper and re-download the small model its outdated
